[project]
name = "simulation-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.0"
dependencies = [
    "numpy>=2.2.3",
    "ollama>=0.4.7",
    "pandas>=2.2.3",
    "pypdf2>=3.0.1",
    "torch>=2.6.0",
]
